### ISSUE TITLE
npm ERR! corona-tracker@0.1.0 start: `react-app-rewired start` npm ERR! Exit status 1 npm ERR! npm ERR! Failed at the corona-tracker@0.1.0 start script.

### ISSUE THREAD

**Issue by jchen42703** [COVID-19-electronic-health-system/Corona-tracker#125]
# Note
I will running everything on a fresh install tomorrow just in case this is just a problem with my installation of the repository's npm modules.

### Prerequisites
* [ ] Reproduced the problem in QA
* [ ] Followed all applicable steps in the TROUBLESHOOTING guide: TODO
* [x] Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
* [x] Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
Full Log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\jchen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start' ]
2 info using npm@6.14.1
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle corona-tracker@0.1.0~prestart: corona-tracker@0.1.0
6 info lifecycle corona-tracker@0.1.0~start: corona-tracker@0.1.0
7 verbose lifecycle corona-tracker@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle corona-tracker@0.1.0~start: PATH: C:\Users\jchen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\jchen\website_projects\Forks\Corona-tracker\client\node_modules\.bin;C:\Users\jchen\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\jchen\bin;C:\Program Files (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\nodejs;C:\Go\bin;C:\ProgramData\chocolatey\bin;C:\ProgramData\nvm;C:\Program Files\nodejs;C:\Program Files\Java\jdk1.8.0_211\bin;C:\Program Files (x86)\Yarn\bin;C:\Users\jchen\AppData\Local\Programs\Python\Python35\Scripts;C:\Users\jchen\AppData\Local\Programs\Python\Python35;C:\Users\jchen\AppData\Local\Microsoft\WindowsApps;C:\Users\jchen\AppData\Local\atom\bin;C:\Users\jchen\AppData\Local\GitHubDesktop\bin;C:\Users\jchen\AppData\Roaming\npm;C:\Users\jchen\go\bin;C:\Users\jchen\AppData\Local\Microsoft\WindowsApps;C:\Users\jchen\AppData\Local\Programs\Microsoft VS Code\bin;C:\FFmpeg\bin;C:\Users\jchen\AppData\Local\Android\Sdk\platform-tools;C:\Users\jchen\AppData\Local\Yarn\bin;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle corona-tracker@0.1.0~start: CWD: C:\Users\jchen\website_projects\Forks\Corona-tracker\client
10 silly lifecycle corona-tracker@0.1.0~start: Args: [ '/d /s /c', 'react-app-rewired start' ]
11 silly lifecycle corona-tracker@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle corona-tracker@0.1.0~start: Failed to exec start script
13 verbose stack Error: corona-tracker@0.1.0 start: `react-app-rewired start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\jchen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\jchen\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid corona-tracker@0.1.0
15 verbose cwd C:\Users\jchen\website_projects\Forks\Corona-tracker\client
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jchen\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v10.15.3
19 verbose npm  v6.14.1
20 error code ELIFECYCLE
21 error errno 1
22 error corona-tracker@0.1.0 start: `react-app-rewired start`
22 error Exit status 1
23 error Failed at the corona-tracker@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
### Steps to Reproduce
1. Run `mongod` and `mongo` on Windows (where `mongod` and `mongo` are aliases to the `.exe` files).
2. In MongoDB console, run `use coronatracker`.
3. In a separate console, `cd Coronatracker/client` and run `radiks-server`.
4. In a separate console, run `npm run start`.

I did not have this issue when I ran the same procedure this morning.

**Expected behavior:**

Should open up the app.

**Actual behavior:**

The localhost server does not start.

**Reproduces how often:**

100% of the time on my end.

**Comment by jchen42703** [comment]
I no longer encounter this issue, so I will close it. The app opened once I ran yarn commands in `client`.
