### ISSUE TITLE
[Health Log]: Symptom Tracker Survey - Slider 3.22.20

### ISSUE THREAD

**Issue by awu556** [COVID-19-electronic-health-system/Corona-tracker#138]
See wireframe ![Survey Sliders](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/v1-final-MVP/survey-view-sample.png)

- [x] Component 1: Instructions
Instructions/overview/answer truthfully
Disclaimer?

- [x] Q1: How do you feel today?
Slider: 1-10

- [x] Q2:  How are you feeling compared to yesterday?
Better/The Same/Worse

- [x] Q3: How are your symptoms?
Slider: 1-10

- [x] Q4: Which symptoms are you feeling or experiencing?

Only check the box if you exhibit the following symptoms:

- [x] Can you take your temperature?   Yes   No

- [x] Fever                             Enter your temperature here:   0.0 oF

- [x] Let’s check your health for today:
Shortness of breath       [  Minimal  |  Moderate  |  Severe  ]
Persistent pain or pressure in the chest [  Minimal  |  Moderate  |  Severe  ]
Chills                             [  Minimal  |  Moderate  |  Severe  ]
Fatigue                          [  Minimal  |  Moderate  |  Severe  ]
Dry Cough                     [  Minimal  |  Moderate  |  Severe  ]
Sore Throat                   [  Minimal  |  Moderate  |  Severe  ]
Bluish lips or face          [  Minimal  |  Moderate  |  Severe  ]
New confusion or inability to arouse [  Minimal  |  Moderate  |  Severe  ]
Other:                           [                                                      ]
  

- [x] Enter more questions: [click and drop-down appears]:
Headache                   [  Minimal  |  Moderate  |  Severe  ]
Diarrhea 
Gastrointestinal issues  [  Minimal  |  Moderate  |  Severe  ]
Examples: nausea, diarrhea, vomiting, abdominal pain.
Loss of smell and/or taste    [  Minimal  |  Moderate  |  Severe  ]

**Comment by awu556** [comment]
Nice job Pavel!
